// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hoypculkjqwecofdlyhk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhveXBjdWxranF3ZWNvZmRseWhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxMTA0NjgsImV4cCI6MjA3NDY4NjQ2OH0.TYVOispQRHuV52PHnUMe4SHxbzMGSWG8-b4XjMq91Ls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});